name: 'Setup postgres'
description: 'Setup postgres with provided settings'
inputs:
  POSTGRES_HOST:  # id of input
    description: 'postgres_host'
    required: true
    default: 'localhost'
  POSTGRES_PORT: # id of post
    description: 'postgres_port'
    required: true
    default: '5432'
runs:
  using: 'node12'
  main: 'index.js'