name: 'Postgres client with custom settings'
description: 'Setup postgres client with provided settings'
author: 'Oxfos'
branding:
  icon: 'database'
  color: 'green'
inputs:
  POSTGRES_HOST:  # id of input
    description: 'postgres_host'
    required: true
    default: 'localhost'
  POSTGRES_PORT: # id of post
    description: 'postgres_port'
    required: true
    default: '5432'
  POSTGRES_USER: # User
    description: 'postgres_user'
    required: false
    default: 'postgres'
  POSTGRES_PASSWORD: # Password
    description: 'postgres_password'
    required: false
    default: 'postgres'
  POSTGRES_DB: # database
    description: 'postgres_db'
    required: false
    default: 'postgres'
runs:
  using: 'node12'
  main: 'index.js'
